---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-cart-payment

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false

resources:
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: shopping-cart
  app.kubernetes.io/version: "1.0.0"
