---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-cart-payment

labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false

resources:
- serviceaccount.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: shopping-cart
  app.kubernetes.io/version: "1.0.0"

images:
  - name: ghcr.io/your-org/payment-service
    newName: ghcr.io/wilddog64/shopping-cart-payment
    newTag: latest
