---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: shopping-cart-payment
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shopping-cart
    pci-scope: "true"
automountServiceAccountToken: false
